version: "3.8"

services:
  pipeline:
    build: .
    volumes:
      - ./data:/app/data
    command: python3 spark_lag.py

  api:
    build: .
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - pipeline